# Generated by Django 2.1.3 on 2020-07-08 07:20

from django.db import migrations


def insert_default_doc_user(apps, schema_editor):
    '''
        Inserting the default Admin user for initial migration.
    '''
    User = apps.get_model('auth', 'User')
    User.objects.create(username="admin", email="admin@admin.com",
                        first_name="System", last_name="Admin",
                        is_superuser=True, is_active=True, is_staff=True,
                        password="pbkdf2_sha256$120000$JwOZYMTFrt45$J2tF/ekXRviaS+GKLDunKc9VjNx2CFRjttDmAj8LfwM=")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_doc_user),
    ]
